version: '1.0'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: knowslog-crawler-db
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./script/initdb:/docker-entrypoint-initdb.d
    env_file: 
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5433:5432"

volumes:
  app-db-data: