"""empty message

Revision ID: 0406d8157638
Revises: a770c2bf4eaa
Create Date: 2024-08-01 17:08:06.270375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0406d8157638'
down_revision: Union[str, None] = 'a770c2bf4eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userllm',
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('delete_yn', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('active_yn', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['userapikey.id'], ),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('userusage', sa.Column('user_llm_id', sa.Integer(), nullable=False))
    op.drop_constraint('userusage_api_id_fkey', 'userusage', type_='foreignkey')
    op.drop_constraint('userusage_user_id_fkey', 'userusage', type_='foreignkey')
    op.drop_constraint('userusage_llm_id_fkey', 'userusage', type_='foreignkey')
    op.create_foreign_key(None, 'userusage', 'userllm', ['user_llm_id'], ['id'])
    op.drop_column('userusage', 'user_id')
    op.drop_column('userusage', 'api_id')
    op.drop_column('userusage', 'llm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userusage', sa.Column('llm_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('userusage', sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('userusage', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userusage', type_='foreignkey')
    op.create_foreign_key('userusage_llm_id_fkey', 'userusage', 'llm', ['llm_id'], ['id'])
    op.create_foreign_key('userusage_user_id_fkey', 'userusage', 'user', ['user_id'], ['id'])
    op.create_foreign_key('userusage_api_id_fkey', 'userusage', 'userapikey', ['api_id'], ['id'])
    op.drop_column('userusage', 'user_llm_id')
    op.drop_table('userllm')
    # ### end Alembic commands ###
