"""empty message

Revision ID: 51b565f7889b
Revises: bae01a23efec
Create Date: 2024-10-15 15:59:34.595600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '51b565f7889b'
down_revision: Union[str, None] = 'bae01a23efec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('archive_embedding_model_id_fkey', 'archive', type_='foreignkey')
    op.drop_column('archive', 'embedding_yn')
    op.drop_column('archive', 'embedding_model_id')
    op.drop_column('archive', 'collection_id')
    op.drop_constraint('userfiles_embedding_model_id_fkey', 'userfiles', type_='foreignkey')
    op.drop_column('userfiles', 'embedding_yn')
    op.drop_column('userfiles', 'embedding_model_id')
    op.drop_column('userfiles', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfiles', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('userfiles', sa.Column('embedding_model_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('userfiles', sa.Column('embedding_yn', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('userfiles_embedding_model_id_fkey', 'userfiles', 'llm', ['embedding_model_id'], ['id'])
    op.add_column('archive', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('archive', sa.Column('embedding_model_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('archive', sa.Column('embedding_yn', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('archive_embedding_model_id_fkey', 'archive', 'llm', ['embedding_model_id'], ['id'])
    # ### end Alembic commands ###
