"""empty message

Revision ID: 63be640444e6
Revises: 68e7f85a9f61
Create Date: 2024-10-15 16:07:33.070682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '63be640444e6'
down_revision: Union[str, None] = '68e7f85a9f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('embedding_yn', sa.Boolean(), nullable=True))
    op.add_column('archive', sa.Column('embedding_model_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('archive', sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'archive', 'llm', ['embedding_model_id'], ['id'])
    op.alter_column('userfiles', 'embedding_yn',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userfiles', 'embedding_yn',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.drop_column('archive', 'collection_id')
    op.drop_column('archive', 'embedding_model_id')
    op.drop_column('archive', 'embedding_yn')
    # ### end Alembic commands ###
