"""empty message

Revision ID: 68e7f85a9f61
Revises: 51b565f7889b
Create Date: 2024-10-15 16:05:52.381802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '68e7f85a9f61'
down_revision: Union[str, None] = '51b565f7889b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfiles', sa.Column('embedding_yn', sa.Boolean(), nullable=False))
    op.add_column('userfiles', sa.Column('embedding_model_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('userfiles', sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'userfiles', 'llm', ['embedding_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfiles', type_='foreignkey')
    op.drop_column('userfiles', 'collection_id')
    op.drop_column('userfiles', 'embedding_model_id')
    op.drop_column('userfiles', 'embedding_yn')
    # ### end Alembic commands ###
