"""empty message

Revision ID: 8d3a5e2b09e9
Revises: 6957eac55426
Create Date: 2024-07-29 15:02:26.070700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8d3a5e2b09e9'
down_revision: Union[str, None] = '6957eac55426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('dom', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archive', 'dom')
    # ### end Alembic commands ###
