"""empty message

Revision ID: a770c2bf4eaa
Revises: 0c3bf40e163b
Create Date: 2024-07-31 15:52:18.590068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a770c2bf4eaa'
down_revision: Union[str, None] = '0c3bf40e163b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'is_active')
    # ### end Alembic commands ###
