"""empty message

Revision ID: bae01a23efec
Revises: bc0208d391b9
Create Date: 2024-10-15 15:48:06.828541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bae01a23efec'
down_revision: Union[str, None] = 'bc0208d391b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('embedding_yn', sa.Boolean(), nullable=True))
    op.add_column('archive', sa.Column('embedding_model_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('archive', sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'archive', 'llm', ['embedding_model_id'], ['id'])
    op.add_column('userfiles', sa.Column('embedding_yn', sa.Boolean(), nullable=True))
    op.add_column('userfiles', sa.Column('embedding_model_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('userfiles', sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'userfiles', 'llm', ['embedding_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfiles', type_='foreignkey')
    op.drop_column('userfiles', 'collection_id')
    op.drop_column('userfiles', 'embedding_model_id')
    op.drop_column('userfiles', 'embedding_yn')
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.drop_column('archive', 'collection_id')
    op.drop_column('archive', 'embedding_model_id')
    op.drop_column('archive', 'embedding_yn')
    # ### end Alembic commands ###
