"""empty message

Revision ID: fede1dcbd7cf
Revises: f111def7dca5
Create Date: 2024-07-22 13:57:56.638588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fede1dcbd7cf'
down_revision: Union[str, None] = 'f111def7dca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'archive', 'user', ['user_id'], ['id'])
    op.add_column('refine', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'refine', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refine', type_='foreignkey')
    op.drop_column('refine', 'user_id')
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.drop_column('archive', 'user_id')
    # ### end Alembic commands ###
